services:
  - type: web
    name: anonmixer-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/contract
    autoDeploy: true 